### ISSUE TITLE
How to use -l option

### ISSUE THREAD

**Issue by Kirti1463** [christianbaun/s3perf#2]
Hi,
I was trying to use -l location option but getting error if i directly use the command 

for **eg**: 
 ./ossperf.sh -n 10 -s 1048576 -b ossperf-testbucket -a -l 
./ossperf.sh: option requires an argument -- l
[ERROR] Invalid option!  

and if i give some random input then also it's executing;

**eg**: ./ossperf.sh -n 10 -s 1048576 -b ossperf-testbucket -a -l 123
[INFO] The tool s3cmd has been found on this system.
s3cmd version 2.0.1
[INFO] The tool bc has been found on this system.
bc 1.07.1
[INFO] The tool md5sum has been found on this system.
md5sum (GNU coreutils) 8.28
[INFO] The tool ping has been found on this system.
ping utility, iputils-s20161105
[INFO] The swift client has been found on this system.
[OK] This computer has a working internet connection.
[OK] The storage service can be accessed via the tool swift.
[OK] The directory testfiles has been created in the local directory.
1048576+0 records in
1048576+0 records out
1048576 bytes (1.0 MB, 1.0 MiB) copied, 2.41526 s, 434 kB/s
[OK] File with random content has been created.
^Z
[3]+  Stopped                 ./ossperf.sh -n 10 -s 1048576 -b ossperf-testbucket -a -l 123

So my question here is whats the right way to use -l option while executing the ossperf command.

**Comment by christianbaun** [comment]
When using the parameter -l, you can specify a bucket location by the region (location) name. Your examples lack this location name.

When using e.g. the Google Cloud Storage, you can specify one of these bucket locations.

https://cloud.google.com/storage/docs/locations

The AWS has also some regions: 

https://docs.aws.amazon.com/general/latest/gr/rande.html

It is similar for most public cloud storage services and private cloud services too.

This Google Cloud Storage example e.g. works well for me:
`./ossperf.sh -n 10 -s 1048576 -b <your_bucket_name> -l europe-west3`

**Comment by Kirti1463** [comment]
I tried running this example but it's throwing .s3cfg error. So can you specify the path for keeping the configuration file and what parameters should be given while configuring the file?

How can we access swift remotely with ossperf and what configurations will be required?

And If m giving the wrong location still it's accepting the input. I think there is no error handling or no error comes up with the wrong input. So could you please check for that as well if there's any modification to be done in the script?

**Comment by christianbaun** [comment]
Can you please post the output with the error message? I mean the output from the command to the error situation.

**Comment by Kirti1463** [comment]
this is the error that i m getting:

 $ ./ossperf.sh -n 10 -s 1048576 -b abx -l europe-west3
[INFO] ossperf will use the tool s3cmd because no other client tool has been specified via command line parameter.
[INFO] The tool s3cmd has been found on this system.
s3cmd version 2.0.1
[INFO] The tool bc has been found on this system.
bc 1.07.1
[INFO] The tool md5sum has been found on this system.
md5sum (GNU coreutils) 8.28
[INFO] The tool ping has been found on this system.
ping utility, iputils-s20161105
[OK] This computer has a working internet connection.
ERROR: /home/poc/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.
[ERROR] Unable to access the storage service via the tool s3cmd.

**Comment by christianbaun** [comment]
With this command string...

`$ ./ossperf.sh -n 10 -s 1048576 -b abx -l europe-west3`

...you tell ossperf to use a bucket with the name `abx` and to place it in a region called `europe-west3`. BWT: This is the name of a region in the Google Cloud Services ecosystem. The ossperf tool will try to connect with `s3cmd` to the storage service and in order to do this, you need to configure s3cmd first.  

s3cmd per default uses the config file ~/.s3cfg. If it is not available (in your case, it is still missing) you can create a new one with the command `s3cmd --configure`.

[Here](https://s3tools.org/usage), you can find more information on how to configure and use [s3cmd](https://s3tools.org/s3cmd). 

In an earlier post, you wrote that you want to access (test the performance) of a Swift storage service.
You can do this with [s3cmd](https://s3tools.org/s3cmd) or by using the [swift client](https://github.com/openstack/python-swiftclient) when using the ossperf command line parameter `-a`. But as precondition you need to have configured the `s3cmd` tool or the wwift client first in order that they can interact with the storage service you want to access. 

Some information on how I managed to start Swift on a single board computer can be found [here](https://github.com/christianbaun/ossperf/wiki/Swift-on-a-Raspberry-Pi-3-with-Raspbian-%28Debian-Jessie-8.0%29).

Some further important background information: The ossperf tool is able to carry out a set of performance tests on storage services, but it cannot access them without the help of a client tool. At the moment, these client tools are supported: [s3cmd](https://github.com/s3tools/s3cmd), [swift](https://github.com/openstack/python-swiftclient), [mc](https://github.com/minio/mc), [az](https://github.com/Azure/azure-cli) and [gsutil](https://github.com/GoogleCloudPlatform/gsutil). In order to use ossperf, you need at least a single one of these client tools deployed on your client system and configured in a way that it can interact with the storage service you want to test.

**Comment by Kirti1463** [comment]
Can you please answer my second question that was : How can we access swift remotely with ossperf and what configurations will be required?

**Comment by christianbaun** [comment]
You need the OSSperf tool and the [swift client](https://github.com/openstack/python-swiftclient) installed on your local client system. The swift client need to be configured in a way that it can access your Swift storage service. You can try if the configuration works on command line with the command `swift list`.

If this works, you can use OSSperf with the [swift client](https://github.com/openstack/python-swiftclient) with commands like this: 

`./ossperf.sh -n 5 -s 1048576 -a `

**Comment by Kirti1463** [comment]
Can you please answer my second question that was : How can we access swift remotely with ossperf and what configurations will be required?
