### ISSUE TITLE
any current benchmarks available?

### ISSUE THREAD

**Issue by wzrdtales** [christianbaun/s3perf#7]
Hey there,

thank you for putting this together :)

I wanted to know if there are any current benchmarks, since the last published one is quite outdated. Otherwise I will see to setup one on my own.

**Comment by christianbaun** [comment]
Hello Tobias,

I did not upload many benchmarks because they depend mainly on your internet connection speed (if you plan to evaluate a public storage service) or on the hardware of your (private) storage service. It is the best option to do a test run with your client machine to evaluate the service you plan to investigate. And it is not difficult. If you need assistance, don't hesitate to ask here. 

Best regards
   Christian

**Comment by wzrdtales** [comment]
also while i not agree that it depends on your connection speed, benchmarks always go under a setup assumptions with "no bottleneck" on the network, I can certainly do it myself. I just wanted to see if I can save the time to make a comparable setup of each of the different contenders.

**Comment by wzrdtales** [comment]
to be more precise I anyways am just looking for how good swift s3 has evolved over the last 3 years. that minio is and keeps the strongest in performance is not a secret.
